// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbXGlkx24CC8Xm7r8MMUgr4v_wBBB-Ngg',
    appId: '1:622432951544:ios:c14b8caa0efc5e90532f0d',
    messagingSenderId: '622432951544',
    projectId: 'redditclone-dc224',
    storageBucket: 'redditclone-dc224.appspot.com',
    iosBundleId: 'com.example.redditTutorial',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAifWobGF9kW41qiVD3Xp-qBl-tCSUovd0',
    appId: '1:622432951544:web:b6ae211095374e95532f0d',
    messagingSenderId: '622432951544',
    projectId: 'redditclone-dc224',
    authDomain: 'redditclone-dc224.firebaseapp.com',
    storageBucket: 'redditclone-dc224.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbXGlkx24CC8Xm7r8MMUgr4v_wBBB-Ngg',
    appId: '1:622432951544:ios:c14b8caa0efc5e90532f0d',
    messagingSenderId: '622432951544',
    projectId: 'redditclone-dc224',
    storageBucket: 'redditclone-dc224.appspot.com',
    iosBundleId: 'com.example.redditTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAifWobGF9kW41qiVD3Xp-qBl-tCSUovd0',
    appId: '1:622432951544:web:85c211c445a6daf1532f0d',
    messagingSenderId: '622432951544',
    projectId: 'redditclone-dc224',
    authDomain: 'redditclone-dc224.firebaseapp.com',
    storageBucket: 'redditclone-dc224.appspot.com',
  );

}